### ISSUE TITLE
Assignment 1 - List of tasks

### ISSUE THREAD

**Issue by adithyaselv** [airavata-courses/CAPtivate#5]
We must develop the following services: 
- [x] Data Retrieval Service #6 
- [x] Model Execution Service #7 
- [x] Post-Processing and Analysis Service #8 
- [x] User Management Service #9 
- [x] Session Management Service #32 
- [x] API Server #10 
- [x] Web Interface #16 
- [x] Each service must run as a separate process that communicates over network connections.
- [x] You must use at least 3 different programming languages For example, one service in Python, one in Go, one in Java, ...
- [x] You must use at least one DB technology
- [x] Only one microservice can connect to each DBMS
- [x] You must choose and implement an internal communication strategy for your microservices, including internal service APIs and/or message formats and data models for each service’s inputs and outputs. 
- [x] You must define your API based on this lecture and other discussions
- [x] You must provide a continuous integration and deployment system for deploying your services #14 
- [x] The entire system must work end-to-end
- [x] Users must be able to log into the web interface
- [x] Users must be able to provide inputs, submit a data retrieval-model execution-analysis pipeline.
- [x] User sessions should be recorded and saved
- [ ] Users should be able to view, copy and resubmit previous jobs with new parameters. 
- [x] Your entire system must be easily deployable by your peers, graders, and instructors
